Add warnings if binfmt activation failed

diff --git a/activate b/activate
--- a/activate
+++ b/activate
@@ -31,4 +31,8 @@ export RANLIB=llvm-ranlib
 export AS=llvm-as
 
 # Register Wasmer as a binfmt handler
-$SUDO $WASMER binfmt reregister >/dev/null
+if test $SUDO != "" ; then
+    $SUDO $WASMER binfmt reregister >/dev/null || echo "Warning: Failed to register wasmer as a binfmt handler. You might need to run 'sudo $WASMER binfmt register' manually." >&2
+else
+    $WASMER binfmt reregister >/dev/null || echo "Warning: Failed to register wasmer as a binfmt handler. You might need to run 'sudo $WASMER binfmt register' manually." >&2
+fi
