Add check for dependencies to activation scripts

diff --git a/activate b/activate
--- a/activate
+++ b/activate
@@ -2,6 +2,14 @@
 
 WASIX_CLANG_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
 
+if ! test -f $WASIX_CLANG_DIR/.dependencies-ok ; then
+    echo "You are running wasix-clang for the first time. This will take a moment, as we need to fetch dependencies." >&2
+    if ! bash $WASIX_CLANG_DIR/setup.sh ; then
+        echo "Failed to set up dependencies. Please check the output above for errors." >&2
+        exit 1
+    fi
+fi 
+
 if test -z "$SUDO" && test "$(id -u)" -ne 0 ; then
     SUDO="$(which sudo)"
 fi
